smac_planner: fix goal checking in getAnalyticPath()
ros-planning/navigation2 pull request #2159
Opened 2021-01-28 09:24 UTC by mkolodziejczyk-piap

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #2040 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | my own simulation stack |

---

## Description of contribution in a few bullet points

* Added condition to exclude goal from poses added through analytic path expansion, because the goal is added always at the end and adding it twice causes infinite loops in the path

2021-01-28 16:12 UTC, SteveMacenski requested changes
Just a styling change but LGTM. Can you explain in a few sentences what the specific issue you hit? I'm curious how we didn't also run into this in our testing.

2021-01-28 16:12 UTC, SteveMacenski commented on smac_planner/src/a_star.cpp
> +    if (!n->wasVisited() and n->getIndex()!=_goal->getIndex()) {
```suggestion
    if (!n->wasVisited() && n->getIndex() != _goal->getIndex()) {
```

Just to be consistent in styling

2021-01-29 10:18 UTC, mkolodziejczyk-piap commented
IMO the issue arises, when the vehicle is crossing the goal but the orientation is not the goal orientation and after crossing this goal ompl plans to correct the yaw with some back and forth manouvers. In my case, this loop happend almost all the time near the goal, probably because (1) my controller was not tuned enought to follow the path exactly (so the initial "smooth" global plan turned into some wild manouvers to correct the yaw) (2) my vehicle has large turning radius

2021-01-29 18:02 UTC, SteveMacenski commented
> vehicle is crossing the goal but the orientation is not the goal orientation

Ooooooh, yeah I did _not_ test for that. Thanks!

Please make the update / `main` PR and we can merge the set.

2021-02-03 00:19 UTC, SteveMacenski commented
@mkolodziejczyk-piap just following up here. Just need the small styling update & `main` PR to merge both

2021-02-09 22:23 UTC, SteveMacenski commented
@mkolodziejczyk-piap just following up

This is essentially done, just needs superficial update

2021-02-24 06:51 UTC, SteveMacenski commented
Closing - superseded by linked PRs

2021-02-24 06:51 UTC, closed without merging