Hot fix rrp slow
ros-planning/navigation2 pull request #2526
Opened 2021-08-20 20:15 UTC by padhupradheep

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #2332  |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | mp-400 from Neobotix |

---

## Description of contribution in a few bullet points

* Fixed the segfault issue that occurred when the robot was set to drive at high speed using RPP. 

## Description of documentation updates required from your changes

NA

---

## Future work that may be required in bullet points

NA

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2021-08-20 20:40 UTC, SteveMacenski requested changes

2021-08-20 20:40 UTC, SteveMacenski commented on nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
> +      "The dimensions of the costmap is too small to fully include your robot's footprint"
Needs a space and a comma, the line extension doesn't add a space between the words

2021-08-20 20:40 UTC, SteveMacenski commented on nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
> +      "The dimensions of the costmap is too small to fully include your robot's footprint"
as well below

2021-08-20 20:40 UTC, SteveMacenski commented on nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
> +      "The dimensions of the costmap is too small to fully include your robot's footprint"
and above

2021-08-24 00:48 UTC, SteveMacenski commented
@padhupradheep last thing here is just string formatting, then good to go!

2021-08-24 08:11 UTC, padhupradheep commented
> @padhupradheep last thing here is just string formatting, then good to go!

Done @SteveMacenski

2021-08-24 18:50 UTC, SteveMacenski approved these changes

2021-08-24 18:50 UTC, merged

2021-08-24 18:51 UTC, SteveMacenski commented
Thanks!!