Shim controller
ros-planning/navigation2 pull request #2579
Opened 2021-10-04 08:21 UTC by melkobrodov

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #2064 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | gazebo simulation of turtlebot3 |

---

## Description of contribution in a few bullet points

* I added shim controller plugin

## Description of documentation updates required from your changes

* I added parameters, need to document them in Configuration Guide section
* Also I added tutorial in General Tutorials

---

## Future work that may be required in bullet points

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2021-10-04 19:15 UTC, SteveMacenski requested changes
Code looks clean for the most part, just need to pare it down to the necessary minimum components and simplify it. Our goal is just a plugin that rotates a robot to the rough path heading once a new path comes in, and when at the goal pose. Otherwise, give it to the controller plugin to track the path. Overall, this should be a relatively simple passthrough file with some block of rotate to heading logic.

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_bringup/params/nav2_sc_params.yaml
> +amcl:
Remove this param file

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
This shouldn't be necessary, what C++17 feature are you using?

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/include/nav2_shim_controller/shim_controller.hpp
> +// Copyright (c) 2020 Shrijit Singh
This package is missing a readme file explaining what it is, how to use it, why you want to use it, parameters in it, etc.

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/include/nav2_shim_controller/shim_controller.hpp
> +  double desired_linear_vel_;
Many of these parameters should not exist, there's no need for this param, or look ahead dist, or most of them below. This controller only needs a param for max angular velocity / acceleration for rotating to heading / path.

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/src/shim_controller.cpp
> +  if (default_plugin) {default_plugin->cleanup();}
Expand onto multiple lines (and for all cases of this below) to match styling of the rest of the program.

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/src/shim_controller.cpp
> +  if (default_plugin) {default_plugin->cleanup();}
Also need to `reset()` the pointer, I believe in cleanup.

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/src/shim_controller.cpp
> +geometry_msgs::msg::TwistStamped ShimController::calcCmdVel(
Put this function into `computeVelocityCommands`, there's no real reason to separate this out.

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/src/shim_controller.cpp
> +geometry_msgs::msg::TwistStamped ShimController::calcCmdVel(
Then goal_checker doesn't need to be a class member anymore

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/src/shim_controller.cpp
> +  if (speed_limit == nav2_costmap_2d::NO_SPEED_LIMIT) {
This should all just be a pass through to the sub-plugin, there's no need for any of this logic here.

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/src/shim_controller.cpp
> +  const double & lookahead_dist,
This function is unneeded, remove

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/src/shim_controller.cpp
> +  const geometry_msgs::msg::PoseStamped & pose)
This function is unneeded, remove

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/src/shim_controller.cpp
> +  const std::string frame,
This function is unneeded, remove

2021-10-04 19:15 UTC, SteveMacenski commented on nav2_shim_controller/src/shim_controller.cpp
> +  auto transformed_plan = transformGlobalPlan(pose);
Remove all RPP logic, I don't see why that should be in the file that simply rotates a robot to its current path / goal headings

2021-10-05 13:19 UTC, AlexeyMerzlyakov reviewed
I would like agree with Steve's main comment: it looks like we could do without `transformGlobalPlan()/getLookAheadPoint()` PRR's functions as knowing current robot pose and global path should be enough for decisions making to rotate and won't break any current logic, as currently it relies on predicted `carrot_pose` on one step ahead which could be calculated as tangent to global path.

2021-10-05 13:19 UTC, AlexeyMerzlyakov commented on nav2_shim_controller/src/shim_controller.cpp
> +  }
Where is this logic used? It looks, like `desired_linear_vel_` is unused at all: we could just call `default_plugin->setSpeedLimit()`, I think

2021-10-05 17:06 UTC, SteveMacenski commented on nav2_shim_controller/src/shim_controller.cpp
> +  auto transformed_plan = transformGlobalPlan(pose);
The only time you need to do any of this logic is when a new path comes in. So in the set plan function, you could set a flag that it has changed (or compare the paths to see that there is a change) to then trigger the "check if I even need to rotate to rough heading" logic. If not, just pass through and reset the flag. If so, rotate to heading. Once rotated within the tolerance, reset the flag as pass through to the internal controller plugin.

2021-11-30 22:01 UTC, SteveMacenski commented
Hi,

Unfortunately, this is needed a bit more immediately for a project so I'm planning on tackling this this week in order to get it done and merged in before year's end. I'll leave this PR open in case you get a chance to fix it before I'm done, but I'm targeting Friday for a PR to resolve this feature request.

2021-12-01 01:45 UTC, SteveMacenski commented
https://github.com/ros-planning/navigation2/pull/2718

2021-12-01 01:45 UTC, closed without merging