Fix: bt_navigator crashes on lc transitions
ros-planning/navigation2 pull request #2848
Opened 2022-03-16 15:07 UTC by guilyx

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |  #2847 ||
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Our Robot - but this doesn't require moving. I'll test on Steve's simulation later this week |

---

## Description of contribution in a few bullet points

* Transitioning bt_navigator to the unconfigured state crashed in haltAllActions because the XML file path was wrong. When cleaning up one of the navigators, an empty root node was accessed which crashed the node.
* If the root node is an empty pointer I considered that nothing has to be alted - tell me if you also want the transition to fail?
* When we do manage to clean up the node, if we try to configure it again the node will crash because we're redeclaring an existing parameter without checking if it exists.

## Future work that may be required in bullet points

* When calling createTreeFromFile, we may want to check if rootNode is empty and send a warning if it is.
* Might be worth it to try and transition the states of each nodes to see if there are some misbehaviors here and there, I could do that.

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2022-03-16 18:52 UTC, SteveMacenski requested changes
LGTM, just small  changes

2022-03-16 18:52 UTC, SteveMacenski commented on nav2_bt_navigator/src/navigators/navigate_through_poses.cpp
>    std::string pkg_share_dir =
This needs indentation for a bunch of lines you added to an if statement

2022-03-16 18:52 UTC, SteveMacenski commented on nav2_behavior_tree/src/behavior_tree_engine.cpp
> +  if (!root_node) return;
Extend to use brackets / multiple lines for styling of the codebase

2022-03-21 10:32 UTC, guilyx commented
@SteveMacenski should be ready

2022-03-21 15:46 UTC, SteveMacenski approved these changes

2022-03-21 15:47 UTC, merged

2022-03-21 15:47 UTC, SteveMacenski commented
Thanks for the help!