server_respawn_lifecycleNode
ros-planning/navigation2 pull request #2894
Opened 2022-04-07 12:14 UTC by iampaulidrobo

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #2752 ) |
| Primary OS tested on | (Ubuntu 20.04) |
| Robotic platform tested on | (Turtlebot3 simulation) |

---

## Description of contribution in a few bullet points
*The lifecycle manager gets a heartbeat timeout and restarts all the nodes, making the system working again.

## Description of documentation updates required from your changes
1)All node set to respawn true ,to make node running again in case of failure.
2)Lifecycle manager node edited with checking for CONFIGURE and ACTIVATE, and do them in case they are not ACTIVATED.

---

## Future work that may be required in bullet points
1)Reverse transition for the lifecycle nodes to function with modularity.

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2022-04-07 18:26 UTC, SteveMacenski requested changes

2022-04-07 18:26 UTC, SteveMacenski commented on nav2_bringup/bringup/launch/localization_launch.py
> +                        {'autostart': True},
Revert, autostart is a parameterization

2022-04-07 18:26 UTC, SteveMacenski commented on nav2_bringup/bringup/launch/navigation_launch.py
> -                        {'autostart': autostart},
Revert

2022-04-07 18:26 UTC, SteveMacenski commented on nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
> +  class LifecycleManager : public rclcpp::Node
Replace original formatting

2022-04-07 18:27 UTC, SteveMacenski commented
This PR is critically flawed, we should discuss in the ticket. This does not in any way check or aware of the servers failing, its just naively just always trying to bring up, not only when a server was respawned due to a crash. This would cause a critical looping error if we wanted to bring down the lifecycle system safely.

2022-04-07 18:27 UTC, closed without merging

2022-04-08 15:23 UTC, iampaulidrobo commented
Yes,sure.
The server comes up whenever any one node goes down.
@SteveMacenski