Added mutex to prevent SEGFAULT on map change
ros-planning/navigation2 pull request #2933
Opened 2022-05-04 09:41 UTC by mrmara

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (#2931 ) |
| Primary OS tested on | Ubuntu 20.04.3 LTS |
| Robotic platform tested on | Simulation |

---

## Description of contribution in a few bullet points
Fixed Segmentation Fault happening in map_calc_range() if new laserscans were processed during a map change event.
This was done by adding ```configuration_mutex_``` lock on laserscan callback. Mutex lock has been added also to other methods accordingly to ROS Noetic implementation

## Description of documentation updates required from your changes
none

---

## Future work that may be required in bullet points

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2022-05-04 17:43 UTC, SteveMacenski requested changes
I think we can rename one of these mutexes to just the `mutex_` and that's used in all of the places that these 2 are used. There's no reason to have both locked in all situations. 

Also, if we already had `pf_mutex_` locked in all these places, how did adding the configuration mutex fix your issue?

2022-05-05 07:45 UTC, mrmara commented
> I think we can rename one of these mutexes to just the `mutex_` and that's used in all of the places that these 2 are used. There's no reason to have both locked in all situations.

Yes, you are right! I just pushed the modifications.
Anyway, the automatic tests keep failing but I do not understand what is wrong, is it normal?

2022-05-05 08:29 UTC, padhupradheep commented
> Anyway, the automatic tests keep failing but I do not understand what is wrong, is it normal?

In short, you do not have to worry about it.. :-)

2022-05-05 17:10 UTC, SteveMacenski approved these changes

2022-05-05 17:11 UTC, merged