Added costmap in goal_checker plugins
ros-planning/navigation2 pull request #2965
Opened 2022-05-24 07:15 UTC by hardesh

Addresses https://github.com/ros-planning/navigation2/issues/2939 

Tested the build with ROS2 Humble

2022-05-24 19:02 UTC, SteveMacenski requested changes
LGTM conceptually, just a couple of tiny changes.

The biggest thing that also needs updated are 
- Migration guide entry that we made this change

2022-05-24 19:02 UTC, SteveMacenski commented on nav2_controller/include/nav2_controller/plugins/simple_goal_checker.hpp
> +  std::shared_ptr<nav2_costmap_2d::Costmap2DROS> costmap_ros_;
You don't need to store if its not going to be used. In the `cpp` file just change `costmap_ros` to `/*costmap_ros*/` to make the linters happy (so no arguments unused)

2022-05-26 14:04 UTC, hardesh commented on nav2_core/include/nav2_core/goal_checker.hpp
> +    const std::shared_ptr<nav2_costmap_2d::Costmap2DROS> &) = 0;
ahh interesting. did not know about this

2022-05-26 19:00 UTC, SteveMacenski approved these changes
LGTM, please add a section to the migration guide about the API change to the goal checkers https://navigation.ros.org/migration/Galactic.html

2022-05-27 15:00 UTC, hardesh commented
I've opened a PR in the docs repository. Missed it yesterday

2022-05-27 18:01 UTC, SteveMacenski commented
You have a linting error but then can merge

```

-  const std::shared_ptr<nav2_costmap_2d::Costmap2DROS> /*costmap_ros*/)
+  const std::shared_ptr<nav2_costmap_2d::Costmap2DROS>/*costmap_ros*/)
```

2022-05-27 19:36 UTC, merged