Added real frequency to log
ros-planning/navigation2 pull request #3076
Opened 2022-07-14 08:28 UTC by tonynajjar

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | N/A |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Own gazebo simulation |

---

## Description of contribution in a few bullet points

* I added logging of the real achieved frequency when the target is not reached. Context: we were getting the "Control loop missed" warning but wanted to know at what rate we are running to know over time if this gets worse.

It's unfortunate that rclcpp::WallRate doesn't offer a way to get the achieved period/frequency when sleep returns fals

## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2022-07-14 09:11 UTC, tonynajjar commented
![image](https://user-images.githubusercontent.com/14879660/178947028-957c1b9e-8b13-44b4-a68b-768b80ca01e8.png)

I sometimes get frequencies higher than the target one. Any idea why? Maybe because I'm using a separate clock?

2022-07-14 18:30 UTC, SteveMacenski approved these changes

2022-07-14 18:32 UTC, SteveMacenski requested changes

2022-07-14 18:32 UTC, SteveMacenski commented on nav2_controller/src/controller_server.cpp
> +        real_frequency =
This does not appear to be following the styling of the project (I see indents with 4 spaces, things being aligned pythonically, etc. 

Please lint this with ament_uncrustify / ament_cpplint for styling

2022-07-14 19:09 UTC, tonynajjar commented
on it

2022-07-14 19:42 UTC, tonynajjar commented
I applied all your suggestions but still same result...
![image](https://user-images.githubusercontent.com/14879660/179069450-20cf52a3-26d8-4f52-a11b-9f29ad8db92a.png)

I commited the version with the ROS clock. I'm still investigating

2022-07-14 22:54 UTC, SteveMacenski commented
It doesn't seem like this is something we should merge if it doesn't strictly speaking... work :frowning:

2022-07-14 23:05 UTC, tonynajjar commented
I actually agree, unless the wallrate is actually unstable and this only exposes that. I doubt it though, will investigate a bit more tomorrow

2022-07-18 18:30 UTC, tonynajjar commented
I can't find what's wrong and can't spend more time on it. I'm fine to close this PR if you want

2022-07-18 18:37 UTC, SteveMacenski commented
OK :frowning_face: I understand.

2022-07-18 18:37 UTC, closed without merging