Fix for #3078, fix image path in YAML
ros-planning/navigation2 pull request #3082
Opened 2022-07-20 15:09 UTC by nakai-omer

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #3078  |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Own robot |

---

## Description of contribution in a few bullet points

* Extraced only the image file name instead of the whole path when saving the meta data YAML file. 

## Description of documentation updates required from your changes
N/A

---

## Future work that may be required in bullet points
I wanted to avoid having to add another dependency, but it could also be done using std::filesystem, like here: https://en.cppreference.com/w/cpp/filesystem/path/filename

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2022-07-20 17:51 UTC, SteveMacenski requested changes

2022-07-20 17:51 UTC, SteveMacenski commented
I'm asking @AlexeyMerzlyakov to take charge on this one since I leave for PTO in a short period of time. Feel free to merge once you're happy with it and close the ticket.

2022-07-21 09:27 UTC, AlexeyMerzlyakov reviewed
The `find_last_of("/\\");` will find the last entrance of both Linux `/` and Windows `\` in file path, so it will work. During the saving map through MapIO library, saved image file name will now always be relative (the same) to the YAML directory, which will also provide the portability of such saved maps.

Please correct Steve's comment and one nit from my side; and this should be OK to go.

2022-07-21 09:27 UTC, AlexeyMerzlyakov commented on nav2_map_server/src/map_io.cpp
> +    int file_name_index = mapdatafile.find_last_of("/\\");
Please change `int` -> `const int` to intentionally tell the compiler that this variable could be optimized out

2022-07-21 15:06 UTC, AlexeyMerzlyakov approved these changes
LGTM!

2022-07-21 15:59 UTC, SteveMacenski approved these changes

2022-07-21 15:59 UTC, merged