preempt/cancel test for time behavior, spin pluguin
ros-planning/navigation2 pull request #3301
Opened 2022-11-26 23:07 UTC by stevedanomodolor

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here ) |
| Primary OS tested on | (Ubuntu) |
| Robotic platform tested on | (Simulation) |

---

## Description of contribution in a few bullet points
* include preempt/cancel test for time behavior, in the spin plugin

## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2022-11-28 19:22 UTC, SteveMacenski commented
Make sure to run `ament_cpplint` and `ament_uncrustify` locally - there are a number of linting failures

2022-11-28 19:26 UTC, SteveMacenski requested changes
Other than CI failures due to linting, this looks good to me!

2022-11-28 19:26 UTC, SteveMacenski commented on nav2_system_tests/src/behaviors/spin/spin_behavior_tester.hpp
> +    bool wait_action = true,
Can we rename this to `nonblocking_action` to be more clear for myself when I read this in a few years :laughing:

2022-11-29 00:25 UTC, SteveMacenski commented
The tests you added are failing in CI

2022-11-29 06:27 UTC, stevedanomodolor commented
> The tests you added are failing in CI

I just noticed the reason why, I actually thought that preempt returned true, but based on the code it returns false. I will add a comment for future reference. https://github.com/ros-planning/navigation2/blob/a392a17809178a1b1fd2bdbaca6204b579c5a81a/nav2_behaviors/include/nav2_behaviors/timed_behavior.hpp#L223

2022-11-29 12:36 UTC, stevedanomodolor commented
Ci issue fixed

2022-11-29 18:41 UTC, SteveMacenski commented
mhm, the code coverage doesn't show this as being covered https://app.codecov.io/gh/ros-planning/navigation2/blob/tests%2Frecovery_behaviors_cancel_preempt/nav2_behaviors/include/nav2_behaviors/timed_behavior.hpp

Can you check the logs of your tests? Do you see those logs in the preempt / cancel condition being listed on the screen? I suspect something's not quite right here

2022-11-29 19:24 UTC, stevedanomodolor commented
Actually it does. It is strange that it does not appear in the coverage
```
24: [test_spin_behavior_fake_node-6] [INFO] [1669705889.232778337] [spin_behavior_test]: Spin action server is ready
24: [test_spin_behavior_fake_node-6] [ RUN      ] SpinBehaviorTestFixture.testSpinPreemption
24: [test_spin_behavior_fake_node-6] [INFO] [1669705894.234137257] [spin_behavior_test]: Found current robot pose
24: [test_spin_behavior_fake_node-6] [INFO] [1669705894.234233839] [spin_behavior_test]: Init Yaw is 0.000000
24: [test_spin_behavior_fake_node-6] [INFO] [1669705894.234259843] [spin_behavior_test]: Before sending goal
24: [behavior_server-4] [INFO] [1669705894.335794698] [behavior_server]: Running spin
24: [behavior_server-4] [INFO] [1669705894.336128320] [behavior_server]: Turning 9.42 for spin behavior.
24: [test_spin_behavior_fake_node-6] [INFO] [1669705901.336675454] [spin_behavior_test]: Found current robot pose
24: [test_spin_behavior_fake_node-6] [INFO] [1669705901.336752952] [spin_behavior_test]: Init Yaw is 0.000000
24: [test_spin_behavior_fake_node-6] [INFO] [1669705901.336777119] [spin_behavior_test]: Before sending goal
24: [test_spin_behavior_fake_node-6] [INFO] [1669705901.438115551] [spin_behavior_test]: Waiting for result
24: [behavior_server-4] [ERROR] [1669705901.536428595] [behavior_server]: Received a preemption request for spin, however feature is currently not implemented. Aborting and stopping.
24: [behavior_server-4] [WARN] [1669705901.536627725] [behavior_server]: [spin] [ActionServer] Aborting handle.
24: [behavior_server-4] [INFO] [1669705901.536833768] [behavior_server]: Running spin
24: [behavior_server-4] [INFO] [1669705901.536939212] [behavior_server]: Turning 12.57 for spin behavior.
24: [test_spin_behavior_fake_node-6] [INFO] [1669705902.438720147] [spin_behavior_test]: target_yaw 12.566371
24: [behavior_server-4] [WARN] [1669705902.537220580] [behavior_server]: Collision Ahead - Exiting Spin
24: [behavior_server-4] [WARN] [1669705902.537247797] [behavior_server]: spin failed
24: [behavior_server-4] [WARN] [1669705902.537255032] [behavior_server]: [spin] [ActionServer] Aborting handle.
24: [test_spin_behavior_fake_node-6] [INFO] [1669705903.146573041] [spin_behavior_test]: After sending goal
24: [test_spin_behavior_fake_node-6] [ERROR] [1669705903.147398285] [spin_behavior_test]: Goal was aborted
24: [test_spin_behavior_fake_node-6] [       OK ] SpinBehaviorTestFixture.testSpinPreemption (13914 ms)
24: [test_spin_behavior_fake_node-6] [ RUN      ] SpinBehaviorTestFixture.testSpinCancel
24: [test_spin_behavior_fake_node-6] [INFO] [1669705908.148230933] [spin_behavior_test]: Found current robot pose
24: [test_spin_behavior_fake_node-6] [INFO] [1669705908.148308387] [spin_behavior_test]: Init Yaw is 0.000000
24: [test_spin_behavior_fake_node-6] [INFO] [1669705908.148332576] [spin_behavior_test]: Before sending goal
24: [behavior_server-4] [INFO] [1669705908.249599161] [behavior_server]: Running spin
24: [behavior_server-4] [INFO] [1669705908.249771621] [behavior_server]: Turning 12.57 for spin behavior.
24: [test_spin_behavior_fake_node-6] [INFO] [1669705910.250820766] [spin_behavior_test]: Waiting for result
24: [behavior_server-4] [INFO] [1669705910.350111266] [behavior_server]: Canceling spin
24: [behavior_server-4] [WARN] [1669705910.350260623] [behavior_server]: [spin] [ActionServer] Client requested to cancel the goal. Cancelling.
24: [test_spin_behavior_fake_node-6] [INFO] [1669705911.251422358] [spin_behavior_test]: target_yaw 12.566371
24: [test_spin_behavior_fake_node-6] [INFO] [1669705911.967656375] [spin_behavior_test]: After sending goal
24: [test_spin_behavior_fake_node-6] [ERROR] [1669705911.968027722] [spin_behavior_test]: Goal was canceled
24: [test_spin_behavior_fake_node-6] [       OK ] SpinBehaviorTestFixture.testSpinCancel (8821 ms)
24: [test_spin_behavior_fake_node-6] [----------] 2 tests from SpinBehaviorTestFixture (22735 ms total)
24: [test_spin_behavior_fake_node-6] 
24: [test_spin_behavior_fake_node-6] [----------] 7 tests from SpinRecoveryTests/SpinBehaviorTestFixture
24: [test_spin_behavior_fake_node-6] [INFO] [1669705921.988706070] [spin_behavior_test]: Spin action server is ready
24: [test_spin_behavior_fake_node-6] [ RUN      ] SpinRecoveryTests/SpinBehaviorTestFixture.testSpinRecovery/0523599_0100000
24: [test_spin_behavior_fake_node-6] [INFO] [1669705926.989652924] [spin_behavior_test]: Found current robot pose
24: [test_spin_behavior_fake_node-6] [INFO] [1669705926.989746530] [spin_behavior_test]: Init Yaw is 0.000000
24: [test_spin_behavior_fake_node-6] [INFO] [1669705926.989783649] [spin_behavior_test]: Before sending goal
24: [behavior_server-4] [INFO] [1669705927.091160685] [behavior_server]: Running spin
24: [behavior_server-4] [INFO] [1669705927.091376516] [behavior_server]: Turning -0.52 for spin behavior.
24: [test_spin_behavior_fake_node-6] [INFO] [1669705927.091251572] [spin_behavior_test]: Waiting for result
24: [test_spin_behavior_fake_node-6] [INFO] [1669705928.091982664] [spin_behavior_test]: target_yaw -0.523599
24: [test_spin_behavior_fake_node-6] [INFO] [1669705928.120496931] [spin_behavior_test]: After sending goal
24: [behavior_server-4] [INFO] [1669705928.191911727] [behavior_server]: spin completed successfully
24: [test_spin_behavior_fake_node-6] [INFO] [1669705928.192400126] [spin_behavior_test]: result received
24: [test_spin_behavior_fake_node-6] [       OK ] SpinRecoveryTests/SpinBehaviorTestFixture.testSpinRecovery/0523599_0100000 (6204 ms)
24: [test_spin_behavior_fake_node-6] [ RUN      ] SpinRecoveryTests/SpinBehaviorTestFixture.testSpinRecovery/0785398_0100000
24: [test_spin_behavior_fake_node-6] [INFO] [1669705933.193397322] [spin_behavior_test]: Found current robot pose
24: [test_spin_behavior_fake_node-6] [INFO] [1669705933.193477657] [spin_behavior_test]: Init Yaw is 0.000000
24: [test_spin_behavior_fake_node-6] [INFO] [1669705933.193501288] [spin_behavior_test]: Before sending goal
24: [behavior_server-4] [INFO] [1669705933.294702682] [behavior_server]: Running spin
24: [behavior_server-4] [INFO] [1669705933.294895337] [behavior_server]: Turning 0.79 for spin behavior.
24: [test_spin_behavior_fake_node-6] [INFO] [1669705933.294870865] [spin_behavior_test]: Waiting for result
24: [test_spin_behavior_fake_node-6] [INFO] [1669705934.295568028] [spin_behavior_test]: target_yaw 0.785398
24: [test_spin_behavior_fake_node-6] [INFO] [1669705934.336243979] [spin_behavior_test]: After sending goal
24: [behavior_server-4] [INFO] [1669705934.395427608] [behavior_server]: spin completed successfully
24: [test_spin_behavior_fake_node-6] [INFO] [1669705934.395867285] [spin_behavior_test]: result received
24: [test_spin_behavior_fake_node-6] [       OK ] SpinRecoveryTests/SpinBehaviorTestFixture.testSpinRecovery/0785398_0100000 (6204 ms)
24: [test_spin_behavior_fake_node-6] [ RUN      ] SpinRecoveryTests/SpinBehaviorTestFixture.testSpinRecovery/1570796_0100000
24: [test_spin_behavior_fake_node-6] [INFO] [1669705939.396698613] [spin_behavior_test]: Found current robot pose
24: [test_spin_behavior_fake_node-6] [INFO] [1669705939.396775396] [spin_behavior_test]: Init Yaw is 0.000000
24: [test_spin_behavior_fake_node-6] [INFO] [1669705939.396798672] [spin_behavior_test]: Before sending goal
24: [behavior_server-4] [INFO] [1669705939.497967735] [behavior_server]: Running spin
24: [behavior_server-4] [INFO] [1669705939.498199329] [behavior_server]: Turning -1.57 for spin behavior.
24: [test_spin_behavior_fake_node-6] [INFO] [1669705939.498102353] [spin_behavior_test]: Waiting for result
24: [test_spin_behavior_fake_node-6] [INFO] [1669705940.498610263] [spin_behavior_test]: target_yaw -1.570796
24: [test_spin_behavior_fake_node-6] [INFO] [1669705940.585189994] [spin_behavior_test]: After sending goal
24: [behavior_server-4] [INFO] [1669705940.598677738] [behavior_server]: spin completed successfully
24: [test_spin_behavior_fake_node-6] [INFO] [1669705940.599123775] [spin_behavio [...]

2022-11-29 19:31 UTC, SteveMacenski approved these changes

2022-11-29 19:31 UTC, merged

2022-11-29 19:40 UTC, stevedanomodolor commented
After the ci builds, I will into it and see if it takes into consideration the tests and add more test for full coverage for the time_behavior.cpp

2022-11-29 19:43 UTC, SteveMacenski commented
I'm also not really sure what's up with that test failing. I took a quick look and it started failing about a week ago on merging the navigation piping PR from @jwallace42, but I don't think he did anything to cause it. Could be a rolling update sync that broke something. That would also be a nice thing to look at potentially if you wanted! If not, it'll be on my queue in the next week or so. 

```
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/test/plugins/decorator/test_single_trigger_node.cpp:75
Expected equality of these values:
  bt_node_->executeTick()
    Which is: FAILURE
  BT::NodeStatus::RUNNING
    Which is: RUNNING/opt/overlay_ws/src/navigation2/nav2_behavior_tree/test/plugins/decorator/test_single_trigger_node.cpp:77
Expected equality of these values:
  bt_node_->executeTick()
    Which is: FAILURE
  BT::NodeStatus::SUCCESS
    Which is: SUCCESS
```

2022-11-29 19:47 UTC, stevedanomodolor commented
I also noticed that too, I will look into it to see the whats the culprit

2022-11-29 19:52 UTC, SteveMacenski commented
Thanks much! This is a big help!