Set zeros command if timeout
ros-planning/navigation2 pull request #3512
Opened 2023-03-27 09:34 UTC by BriceRenaudeau

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #3481 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | gazebo simulation |

---

## Description of contribution in a few bullet points
 In the timeout check :
* I set the `command_` to zero
* I check if the `last_cmd_` was zero to set the `stopped_` flag to true to stop publishing.

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2023-03-27 12:57 UTC, BriceRenaudeau commented
CI test failed on an other node.
Might not be related.
Please rerun.

2023-03-27 17:14 UTC, SteveMacenski requested changes

2023-03-28 14:58 UTC, BriceRenaudeau commented on nav2_velocity_smoother/src/velocity_smoother.cpp
> +      return;
When you enter the timeout, the robot was moving (else it's already stopped) so the `last_cmd_` is different from zeros.
You don't enter the second if. I set the command to zero as if it received the command hence it applies the deceleration correctly. 
You reach the `return` only if the `last_cmd_` is zero which means the deceleration reached zero.

I tested it and it works well.

2023-03-28 19:42 UTC, SteveMacenski commented on nav2_velocity_smoother/src/velocity_smoother.cpp
> +      return;
I'm looking at a few timesteps of this running:
- We hit a timeout where we receive no new data
- We set the command to a null value and continue on as usual with a `0`ed out velocity. That's set to last command at the end.
- The next round, we're still not receiving new data so we find that last command is zero so we set stopped to `true` and return
- From that point on, we return continuously and never actually enter the body of the function to publish any new commands to apply this node's functionality. So as far as I read this, any such deceleration is just the outcome of your mobile base's handling, not due to this node winding down the velocity profile by the set acceleration limits

This tells me that this is only called for 2 timer cycles after the commands stop coming in, as opposed to 1 before.

2023-03-28 19:50 UTC, SteveMacenski commented on nav2_velocity_smoother/src/velocity_smoother.cpp
> +      return;
You are correct, there are many relatedly named things I wrote in here I got wrapped up in. I agree now that this does that you describe.

2023-03-28 19:51 UTC, SteveMacenski approved these changes

2023-03-29 08:55 UTC, BriceRenaudeau commented
I made a PR to add an entry in the docs:
https://github.com/ros-planning/navigation.ros.org/pull/409

2023-03-29 15:23 UTC, merged

2023-03-29 15:23 UTC, SteveMacenski commented
Thanks!

2023-07-05 23:48 UTC, ufrhaidar commented
why is this `last_cmd_ = *cmd_vel;` moved after the deadband?

If you have a deadband in openloop the machine will get stuck at 0 commanded velocity.

@SteveMacenski @BriceRenaudeau

2023-07-06 07:02 UTC, SteveMacenski commented
The order shouldn't matter since `last_cmd_` isn't used in between. From before, `if (open_loop_) {` still set the same value as such, so there should be absolutely no change in behavior

2023-07-06 07:22 UTC, ufrhaidar commented
> The order shouldn't matter since `last_cmd_` isn't used in between. From before, `if (open_loop_) {` still set the same value as such, so there should be absolutely no change in behavior

It does. If:
- current velocity = `0.0`
- commanded velocity = `0.5`
- max acceleration = `1.0`
- deadband = `0.2`

`applyConstraints()` will make `cmd_vel` be equal to `0.05`, the deadband will make it `0.0`, and then `last_cmd_` will be `0.0`.

You'll end up the same place you started and will get stuck in a loop.

2023-07-10 14:45 UTC, SteveMacenski commented
@BriceRenaudeau can you comment? I think @ufrhaidar has a point

2023-07-10 16:38 UTC, BriceRenaudeau commented
I will check the configuration tomorrow.

My thoughts is that in open loop the previous command is used, so increase at every step and is not stuck. The deadband is only applied to real published command, not the saved one.

2023-07-10 17:08 UTC, BriceRenaudeau commented
There may be an issue.

The line:
https://github.com/ros-planning/navigation2/blob/778c0faee41788c9e3323a420ff2c10122ba4aae/nav2_velocity_smoother/src/velocity_smoother.cpp#L314

Must be above the deadband test, not below.
As I said, I will test that tomorrow.

2023-07-11 08:48 UTC, SteveMacenski commented
If you’re happy open a followup PR to move it and I’ll merge!

2023-07-11 10:36 UTC, BriceRenaudeau commented
I was able to reproduce the issue. The velocity smoother was stuck with a hight deadband (0.2).

The fix is working correctly.

2023-07-12 17:55 UTC, SteveMacenski commented
Thanks for the note!