Backport of the revesing feature for the regulated pure pursuit controller to foxy
ros-planning/navigation2 pull request #3544
Opened 2023-04-27 13:36 UTC by splatter96

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |  |
| Primary OS tested on | Ubuntu 20.04 |
| Robotic platform tested on | gazebo simulation of husky |

---

## Description of contribution in a few bullet points
This is just a backport of the new reversing feature in the pure pursuite controller, which is at the moment only available for galactic and newer. This MR makes this new feature also available for the older foxy branch.

## Description of documentation updates required from your changes

The same documentation as for the galactic and humble branches applies.
That includes the introduction of the `allow_reversing` parameter for this controller.

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2023-04-27 17:01 UTC, SteveMacenski requested changes

2023-04-27 17:03 UTC, SteveMacenski commented
FYI Foxy is super old and is EOL starting in about 3 days. I would **highly** recommend upgrading to literally any more modern distribution. Nav2 has moved mountains since Foxy.

2023-04-28 11:24 UTC, splatter96 commented
For us it is unfortunately not possible to migrate to a newer distribution, as some of the packages we need in our project are only available for foxy, especially the ones from external companies.

But thank you for looking at the MR!

2023-04-28 16:07 UTC, SteveMacenski approved these changes

2023-04-28 16:09 UTC, SteveMacenski requested changes

2023-04-28 16:09 UTC, SteveMacenski commented on nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
> -double clamp(double value, double min, double max) {
Readd, this doesn't even compile

```

04:33:59 -- Build files have been written to: /tmp/ws/build_isolated/nav2_regulated_pure_pursuit_controller
04:33:59 Scanning dependencies of target nav2_regulated_pure_pursuit_controller
04:33:59 [ 50%] Building CXX object CMakeFiles/nav2_regulated_pure_pursuit_controller.dir/src/regulated_pure_pursuit_controller.cpp.o
04:33:59 /tmp/ws/src/navigation2/nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp: In member function ‘double nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController::getLookAheadDistance(const Twist&)’:
04:33:59 /tmp/ws/src/navigation2/nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:226:27: error: ‘clamp’ is not a member of ‘std’
04:33:59   226 |     lookahead_dist = std::clamp(lookahead_dist, min_lookahead_dist_, max_lookahead_dist_);
04:33:59       |                           ^~~~~
04:33:59 /tmp/ws/src/navigation2/nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp: In member function ‘void nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController::rotateToHeading(double&, double&, const double&, const Twist&)’:
04:33:59 /tmp/ws/src/navigation2/nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:336:22: error: ‘clamp’ is not a member of ‘std’
04:33:59   336 |   angular_vel = std::clamp(angular_vel, min_feasible_angular_speed, max_feasible_angular_speed);
04:33:59       |                      ^~~~~
04:33:59 /tmp/ws/src/navigation2/nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp: In member function ‘void nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController::applyConstraints(const double&, const double&, const double&, const Twist&, const double&, double&, double&)’:
04:33:59 /tmp/ws/src/navigation2/nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:509:21: error: ‘clamp’ is not a member of ‘std’
04:33:59   509 |   linear_vel = std::clamp(fabs(linear_vel), 0.0, desired_linear_vel_);
04:33:59       |                     ^~~~~
04:33:59 make[2]: *** [CMakeFiles/nav2_regulated_pure_pursuit_controller.dir/build.make:63: CMakeFiles/nav2_regulated_pure_pursuit_controller.dir/src/regulated_pure_pursuit_controller.cpp.o] Error 1
04:33:59 make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/nav2_regulated_pure_pursuit_controller.dir/all] Error 2
```

2023-04-28 16:09 UTC, SteveMacenski commented
@splatter96 please make sure your changes actually work by testing them after you've made them. Have you tested this at all on your robot hardware to know it works properly?

2023-05-12 12:10 UTC, closed without merging