Runtime polygon enable
ros-planning/navigation2 pull request #3825
Opened 2023-09-19 10:59 UTC by tonynajjar

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3824 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Own gazebo simulation |

---

## Description of contribution in a few bullet points

* Added dynamic enabling/disabling of collision monitor polygons 

## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2023-09-19 11:04 UTC, tonynajjar commented on nav2_collision_monitor/src/polygon.cpp
> +        enabled_ = parameter.as_bool();
setter function better?

2023-09-19 17:13 UTC, SteveMacenski requested changes
Minor changes but LGTM. Some test would be nice though

2023-09-20 05:12 UTC, SteveMacenski commented on nav2_collision_monitor/src/polygon.cpp
> +        enabled_ = parameter.as_bool();
Nope, this is fine!

2023-09-20 08:29 UTC, tonynajjar commented on nav2_collision_monitor/src/collision_monitor_node.cpp
> +      // If the polygon is disabled, skip it
Done. One more question, do you think I should also skip publishing the polygon in `publishPolygons` if it's disabled?

2023-09-20 08:48 UTC, tonynajjar commented
Also, since collision monitor and detector use the same Polygon, detector polygons will also have this new parameter. We could implement the same logic in collision_detector but I don't see much benefit to it except consistency/parallelism between the two nodes. What do you think?

2023-09-25 09:20 UTC, tonynajjar commented
> Doesn't hurt anyone and really easy.

One drawback I see to disabling a polygon in collision_detector is that it would mess up the indexing of polygons in `CollisionDetectorState` msg; if some node subscribing to this topic has saved at initialization that a polygon is at a certain index, then disabling a polygon would cause this node to get the wrong index in `detections` (or even access an index out of range).

The reason why I said I see no value in disabling a polygon in collision detector is because if you don't want the status of a certain polygon, you just don't use it.

If you still think that we should add the functionality and it's safe to expect that the user should always check if `CollisionDetectorState` msg has changed, then I'm fine with implementing it

2023-09-25 10:18 UTC, tonynajjar commented
@SteveMacenski in my last commit I also added the dynamic enabling/disabling of a source

2023-09-25 10:27 UTC, tonynajjar reviewed
I have a general question about dynamic parameter setting: from the Nav2 codebase I see that you prefer having these dynamicParametersCallback in which we set internal member variables with the new parameters.

Another way would be to directly read the parameter from the parameter server, roughly:


```
    auto node = polygon->node_.lock();
    if (!node->get_parameter(polygon->getName() + ".enabled").as_bool()) {
      continue;
    }
```

The benefit here is less boilerplate code. What's the con, is it slower? Or why do you prefer the first option?

2023-09-25 22:43 UTC, SteveMacenski commented
> if some node subscribing to this topic has saved at initialization that a polygon is at a certain index

That's really not good practice and I'd put that into the category of "not our problem". Also, aren't only the polygons in collision published? If so, then there's no order to be assumed because there's no consistent polygon collision. 

> If you still think that we should add the functionality

I do

> dynamicParametersCallback in which we set internal member variables with the new parameters

Because updating a parameter may require reinitializing other areas that parameter is being used in or you could be triggering an action mid-parameter update if trying to update many - so then the state of that action is not fully defined. Further, design wise, its not wise to inject ROS code into your deep algorithm logic, so getting the ROS params and converting to internal types lets you keep ROS out of the library cores + gives you control to explicitly accept or reject parameter updates if they're bogus or invalid, which happens

2023-09-25 22:48 UTC, SteveMacenski commented on nav2_collision_monitor/src/source.cpp
> +  RCLCPP_INFO(logger_, "[%s]: Creating Source", source_name_.c_str());
Remove here and destructor

2023-09-25 22:48 UTC, SteveMacenski commented
@AlexeyMerzlyakov please review

2023-09-26 18:52 UTC, SteveMacenski approved these changes

2023-09-26 18:52 UTC, SteveMacenski commented
@tonynajjar just needs migration guide entry for navigation.ros.org + configuration guide for the new parameters

2023-09-27 09:30 UTC, tonynajjar commented
https://github.com/ros-planning/navigation.ros.org/pull/471

2023-09-27 09:56 UTC, merged

2023-09-27 09:56 UTC, SteveMacenski commented
Great! Thanks! This is nice to have!