Fix bug in nav2_behavior_tree/bt_action_node
ros-planning/navigation2 pull request #3849
Opened 2023-10-01 01:09 UTC by CihatAltiparmak

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #3848 |
| Primary OS tested on | Ubuntu 22.04.3 LTS (Jammy Jellyfish) |
| Robotic platform tested on | - |

---

## Description of contribution in a few bullet points

* Fixed the bug in halt function inside
  nav2_behavior_tree/plugin/action/bt_action_node.hpp

* Added new case to nav2_behavior_tree/plugin/action/bt_action_node.hpp
  for testing the scenario to cancel

* Refactored existing cases in
  nav2_behavior_tree/plugin/action/bt_action_node.hpp

---
## Future work that may be required in bullet points

Test this on simulation platform.

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2023-10-01 23:59 UTC, SteveMacenski requested changes
Overall LGTM with a couple of details.

2023-10-01 23:59 UTC, SteveMacenski commented on nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
> +      if (callback_group_executor_.spin_until_future_complete(future_result) !=
Use the `server_timeout_` as a timeout so its not infinitely blocking

2023-10-01 23:59 UTC, SteveMacenski commented on nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
> +          "Failed to get result call failed :( for [%s]", action_name_.c_str());
```suggestion
          "Failed to get result for %s in node halt!", action_name_.c_str());
```

2023-10-02 15:50 UTC, CihatAltiparmak commented on nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
> +          "Failed to get result call failed :( for [%s]", action_name_.c_str());
Done it in new commit

2023-10-02 17:34 UTC, SteveMacenski approved these changes

2023-10-02 18:17 UTC, merged

2023-10-02 18:17 UTC, SteveMacenski commented
Thanks!