In wait_action node change duration type from int to double
ros-planning/navigation2 pull request #3871
Opened 2023-10-11 11:25 UTC by maksymdidukh

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Gazebo simulation |

---

## Description of contribution in a few bullet points
wait_duration port for Wait node is an integer, so if we pass something like 1.3 or 2.42 than it will automatically cast to nearest integer value, so i changed type of this port from int to double.

## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2023-10-11 11:30 UTC, tonynajjar approved these changes

2023-10-11 11:30 UTC, tonynajjar commented on nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/wait_action.hpp
> +        BT::InputPort<double>("wait_duration", 1, "Wait time")
change the default to 1.0

2023-10-11 11:34 UTC, tonynajjar commented
I wanted to say that the documentation needs updating as well but it looks like it's correct already; there was a mismatch in the code: https://navigation.ros.org/configuration/packages/bt-plugins/actions/Wait.html

2023-10-11 11:37 UTC, tonynajjar commented
Please also modify the test: https://github.com/ros-planning/navigation2/blob/924f167382080f3ccdd000ffc34b921cb64bcf95/nav2_behavior_tree/test/plugins/action/test_wait_action.cpp#L131

2023-10-11 11:41 UTC, maksymdidukh commented
> Please also modify the test:
> 
> https://github.com/ros-planning/navigation2/blob/924f167382080f3ccdd000ffc34b921cb64bcf95/nav2_behavior_tree/test/plugins/action/test_wait_action.cpp#L131

done

2023-10-11 11:46 UTC, tonynajjar commented
There are also a bunch of trees that use Wait with an int, [example](https://github.com/ros-planning/navigation2/blob/924f167382080f3ccdd000ffc34b921cb64bcf95/nav2_bt_navigator/behavior_trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.xml#L40). I know it still works like that and it's not a big deal but it's slightly cleaner imo to have them as doubles as well

2023-10-11 11:47 UTC, tonynajjar approved these changes

2023-10-11 11:51 UTC, maksymdidukh commented
> There are also a bunch of trees that use Wait with an int, [example](https://github.com/ros-planning/navigation2/blob/924f167382080f3ccdd000ffc34b921cb64bcf95/nav2_bt_navigator/behavior_trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.xml#L40). I know it still works like that and it's not a big deal but it's slightly cleaner imo to have them as doubles as well

done))

2023-10-11 16:57 UTC, SteveMacenski commented
@maksymdidukh check CI, you have linting issues: https://app.circleci.com/pipelines/github/ros-planning/navigation2/10176/workflows/cbd18739-840b-42e8-bd73-899603ec4e9d/jobs/32314/tests

Also, this will need documentation updates in the migration guide that we're changing the type of an input. Please open a Migration Guide PR as well

2023-10-11 16:58 UTC, SteveMacenski requested changes

2023-10-11 16:58 UTC, SteveMacenski commented on nav2_behavior_tree/plugins/action/wait_action.cpp
> +  goal_.time.sec = int(duration);
Don't do this. Use `from_seconds`

2023-10-12 12:34 UTC, maksymdidukh commented
> @maksymdidukh check CI, you have linting issues: https://app.circleci.com/pipelines/github/ros-planning/navigation2/10176/workflows/cbd18739-840b-42e8-bd73-899603ec4e9d/jobs/32314/tests
> 
> Also, this will need documentation updates in the migration guide that we're changing the type of an input. Please open a Migration Guide PR as well

here it is https://github.com/ros-planning/navigation.ros.org/pull/476

2023-10-12 12:36 UTC, maksymdidukh commented
failing test is unrelated to my PR

2023-10-12 15:35 UTC, SteveMacenski approved these changes

2023-10-12 15:36 UTC, merged

2023-10-13 08:48 UTC, maksymdidukh commented
@SteveMacenski, could u please backport it to iron?

2023-10-13 15:04 UTC, SteveMacenski commented
Unfortunately no, this breaks ABI using different data types. I’d be OK fudging it for something this minor if you can show that current behavior trees with int’s set in the BT XML still work and are cast correctly. If not, we can’t break everyone’s existing BTs mid-distro