Allow path end pose deviation revive
ros-planning/navigation2 pull request #4065
Opened 2024-01-25 00:31 UTC by jwallace42

This pr revives the work done [here](https://github.com/ros-planning/navigation2/pull/3928) by @pepisg

2024-01-25 17:26 UTC, SteveMacenski commented
I think we were talking about having the param removed and always using the path's final goal as the start to the new?

2024-01-25 19:01 UTC, pepisg commented
> I think we were talking about having the param removed and always using the path's final goal as the start to the new

Yeah, I think that was what we agreed on slack. Also, discussion was gravitating around possible artifacts happening on Lattice. Finally, I wasn't sure how test should look like for this change

2024-01-26 00:51 UTC, SteveMacenski requested changes

2024-01-26 00:51 UTC, SteveMacenski commented on nav2_planner/include/nav2_planner/planner_server.hpp
> +  bool allow_path_through_poses_goal_deviation_;
Unused now :smile:

2024-01-26 00:51 UTC, SteveMacenski commented on nav2_planner/src/planner_server.cpp
> +
remove empty line

2024-01-26 21:22 UTC, SteveMacenski approved these changes

2024-01-26 21:29 UTC, merged